# Jekyll configuration
name : JH Blog
title: JH Blog
lang : ko
lan : ko
description: > # this means to ignore newlines until "baseurl:"
  개발자 박제희
  developer JH

# url is currently only used only for the RSS feed in feed.xml
author :
  name : "박제희"
  email: "pjh2359@gmail.com"
  url: "https://jehuipark.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username: JeHuiPark
GoogleAnalytics: UA-113477172-1

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ""
disqus : 'https-jehuipark-github-io-blog'
comments : true

## default date_format
date_format:
  title: "%Y-%m-%d"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"


disqus_shortname: 'https-jehuipark-github-io-blog' # disqus

twitter:
  username:
facebook:
  app_id: 150481385751381
  publisher:

paginate: 10

##sass:
##    style: compressed

permalink: pretty

highlighter: rouge
markdown: kramdown
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

exclude: ['README.md', 'LICENSE', "*.bak"]

theme: jekyll-theme-cayman
