# Site settings
author : "PJH"
title: JH Blog
email: pjh2359@gmail.com
lang : ko_Kr
description: > # this means to ignore newlines until "baseurl:"
  개발자 박제희
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "https://jehuipark.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username: JeHuiPark
GoogleAnalytics: UA-113477172-1

disqus_shortname: https-jehuipark-github-io-blog # disqus

twitter:
  username:
facebook:
  app_id: 150481385751381
  publisher:

sass:
    style: compressed

permalink: pretty
excerpt_seperator:  <!--break--> #구분자 {{ post.excerpt }}

# Build settings

markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
